version: '3.8'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./conf:/etc/letsencrypt
      - ./webroot:/var/www/certbot
      - ./renew-certs.sh:/renew-certs.sh
    entrypoint: ["sh", "/renew-certs.sh"]
    env_file:
      - .env

